drop table address;
drop table library_page;
drop table navigation_menu;
drop table person;
drop table person_employee;
drop table library_item;
drop table address_country;
drop table search_item;
drop table meeting_category;
drop table person_group;
drop table vacation;
drop table library_faq;
drop table search_item_content;
drop table library_comment;
drop table library_topic;
drop table person_group_right;
drop table person_group_member;
drop table navigation_menu_item;
drop table person_group_right_detail;
drop table meeting_attendee;
drop table search_index;
drop table search_stopword;
drop table library_faq_category;
drop table telecom_address;
drop table calendar_event;
drop table meeting_agenda_point;
drop table person_user;
drop table setting;
drop table meeting;
drop table public_holiday;
create table address (
   id integer not null,
   address_country integer,
   post_code varchar(255),
   region varchar(255),
   street_address varchar(255),
   town varchar(255),
   primary key (id)
);
create table library_page (
   id integer not null generated by default as identity,
   number integer,
   text varchar(255),
   library_item integer,
   search_item integer,
   primary key (id)
);
create table navigation_menu (
   id integer not null generated by default as identity,
   priority integer,
   text varchar(255),
   primary key (id)
);
create table person (
   id integer not null generated by default as identity,
   modified timestamp not null,
   company varchar(255),
   date_of_birth timestamp,
   file_as varchar(255),
   first_names varchar(255),
   person_group integer,
   job_title varchar(255),
   last_name varchar(255),
   salutation varchar(255),
   deleted smallint,
   created timestamp,
   created_by integer,
   modified_by integer,
   primary key (id)
);
create table person_employee (
   id integer not null generated by default as identity,
   address_country integer,
   number varchar(255),
   region_code varchar(255),
   vacation_days integer,
   primary key (id)
);
create table library_item (
   id integer not null generated by default as identity,
   modified timestamp not null,
   image_directory varchar(255),
   summary varchar(255),
   title varchar(255),
   library_topic integer,
   type integer,
   created timestamp,
   created_by integer,
   modified_by integer,
   primary key (id)
);
create table address_country (
   id integer not null generated by default as identity,
   code varchar(255),
   name varchar(255),
   priority integer,
   primary key (id)
);
create table search_item (
   id integer not null generated by default as identity,
   category varchar(255),
   target_id integer,
   type varchar(255),
   primary key (id)
);
create table meeting_category (
   id integer not null generated by default as identity,
   meeting integer,
   name varchar(255),
   primary key (id)
);
create table person_group (
   id integer not null generated by default as identity,
   modified timestamp not null,
   description varchar(255),
   head integer,
   name varchar(255),
   parent integer,
   created timestamp,
   created_by integer,
   modified_by integer,
   primary key (id)
);
create table vacation (
   calendar_event integer not null,
   approved smallint,
   primary key (calendar_event)
);
create table library_faq (
   id integer not null generated by default as identity,
   answer varchar(255),
   library_faq_category integer,
   question varchar(255),
   primary key (id)
);
create table search_item_content (
   id integer not null generated by default as identity,
   search_item integer,
   target_id integer,
   type varchar(255),
   primary key (id)
);
create table library_comment (
   id integer not null generated by default as identity,
   modified timestamp not null,
   format integer,
   item integer,
   id_reply_to integer,
   subject varchar(255),
   text varchar(255),
   no_reply smallint,
   created timestamp,
   created_by integer,
   modified_by integer,
   primary key (id)
);
create table library_topic (
   id integer not null generated by default as identity,
   caption varchar(255),
   image varchar(255),
   primary key (id)
);
create table person_group_right (
   id integer not null generated by default as identity,
   access integer,
   detail integer,
   person_group integer,
   target_id integer,
   primary key (id)
);
create table person_group_member (
   person_group integer not null,
   person_user integer not null,
   primary key (person_user, person_group)
);
create table navigation_menu_item (
   id integer not null generated by default as identity,
   image varchar(255),
   menu integer,
   priority integer,
   text varchar(255),
   URL varchar(255),
   person_user integer,
   primary key (id)
);
create table person_group_right_detail (
   id integer not null generated by default as identity,
   description varchar(255),
   name varchar(255),
   primary key (id)
);
create table meeting_attendee (
   id integer not null generated by default as identity,
   confirmed smallint,
   meeting integer,
   person integer,
   primary key (id)
);
create table search_index (
   id integer not null generated by default as identity,
   content integer,
   weight float,
   word varchar(255),
   primary key (id)
);
create table search_stopword (
   id integer not null generated by default as identity,
   word varchar(255),
   primary key (id)
);
create table library_faq_category (
   id integer not null generated by default as identity,
   description varchar(255),
   library_item integer,
   name varchar(255),
   primary key (id)
);
create table telecom_address (
   id integer not null generated by default as identity,
   modified timestamp not null,
   address varchar(255),
   number integer,
   address_type integer,
   created timestamp,
   created_by integer,
   modified_by integer,
   person integer,
   primary key (id)
);
create table calendar_event (
   id integer not null generated by default as identity,
   modified timestamp not null,
   description varchar(255),
   finish timestamp,
   start timestamp,
   subject varchar(255),
   dayevent smallint,
   created timestamp,
   created_by integer,
   modified_by integer,
   primary key (id)
);
create table meeting_agenda_point (
   id integer not null generated by default as identity,
   category integer,
   minutesText varchar(255),
   name varchar(255),
   primary key (id)
);
create table person_user (
   id integer not null,
   name varchar(255),
   password varchar(255),
   deleted smallint,
   enable smallint,
   primary key (id)
);
create table setting (
   id integer not null generated by default as identity,
   modified timestamp not null,
   description varchar(255),
   name varchar(255),
   type integer,
   person_user integer,
   value varchar(255),
   enable smallint,
   created timestamp,
   created_by integer,
   modified_by integer,
   primary key (id)
);
create table meeting (
   calendar_event integer not null,
   chair_person integer,
   location varchar(255),
   primary key (calendar_event)
);
create table public_holiday (
   calendar_event integer not null,
   country integer,
   region_code varchar(255),
   primary key (calendar_event)
);
alter table address add constraint FKBB979BF4BAAD664B foreign key (address_country) references address_country;
alter table library_page add constraint FK9A17B393DFD7174A foreign key (search_item) references search_item;
alter table library_page add constraint FK9A17B3939A14CC17 foreign key (library_item) references library_item;
alter table person add constraint FKC4E39B55ECF26115 foreign key (person_group) references person_group;
alter table person add constraint FKC4E39B55A3F58D8D foreign key (modified_by) references person_user;
alter table person add constraint FKC4E39B5551A3A90E foreign key (created_by) references person_user;
alter table person_employee add constraint FKEAE56C58BAAD664B foreign key (address_country) references address_country;
alter table library_item add constraint FK9A14CC17A3F58D8D foreign key (modified_by) references person_user;
alter table library_item add constraint FK9A14CC1751A3A90E foreign key (created_by) references person_user;
alter table library_item add constraint FK9A14CC17A91D9CAB foreign key (library_topic) references library_topic;
alter table meeting_category add constraint FK22A1F68238264A3B foreign key (meeting) references meeting;
alter table person_group add constraint FKECF26115C4AB08AA foreign key (parent) references person_group;
alter table person_group add constraint FKECF2611551A3A90E foreign key (created_by) references person_user;
alter table person_group add constraint FKECF2611530CDE0 foreign key (head) references person;
alter table person_group add constraint FKECF26115A3F58D8D foreign key (modified_by) references person_user;
alter table vacation add constraint FK9B8422DD2A9BEA59 foreign key (calendar_event) references calendar_event;
alter table library_faq add constraint FKDBAE09925756890B foreign key (library_faq_category) references library_faq_category;
alter table search_item_content add constraint FKDFDF0884DFD7174A foreign key (search_item) references search_item;
alter table library_comment add constraint FK54B6CEDB6A473294 foreign key (id_reply_to) references library_comment;
alter table library_comment add constraint FK54B6CEDBA3F58D8D foreign key (modified_by) references person_user;
alter table library_comment add constraint FK54B6CEDB317B13 foreign key (item) references library_item;
alter table library_comment add constraint FK54B6CEDB51A3A90E foreign key (created_by) references person_user;
alter table person_group_right add constraint FK2B5CA272B06A1851 foreign key (detail) references person_group_right_detail;
alter table person_group_right add constraint FK2B5CA272ECF26115 foreign key (person_group) references person_group;
alter table person_group_member add constraint FK3779B504E6A2D675 foreign key (person_user) references person_user;
alter table person_group_member add constraint FK3779B504ECF26115 foreign key (person_group) references person_group;
alter table navigation_menu_item add constraint FKBC9B1D8833155F foreign key (menu) references navigation_menu;
alter table navigation_menu_item add constraint FKBC9B1D88E6A2D675 foreign key (person_user) references person_user;
alter table meeting_attendee add constraint FK3FF9063EC4E39B55 foreign key (person) references person;
alter table meeting_attendee add constraint FK3FF9063E38264A3B foreign key (meeting) references meeting;
alter table search_index add constraint FK1B09137B38B73479 foreign key (content) references search_item_content;
alter table library_faq_category add constraint FK5756890B9A14CC17 foreign key (library_item) references library_item;
alter table telecom_address add constraint FK65DD614C51A3A90E foreign key (created_by) references person_user;
alter table telecom_address add constraint FK65DD614CC4E39B55 foreign key (person) references person;
alter table telecom_address add constraint FK65DD614CA3F58D8D foreign key (modified_by) references person_user;
alter table calendar_event add constraint FK2A9BEA5951A3A90E foreign key (created_by) references person_user;
alter table calendar_event add constraint FK2A9BEA59A3F58D8D foreign key (modified_by) references person_user;
alter table meeting_agenda_point add constraint FK93007321302BCFE foreign key (category) references meeting_category;
alter table setting add constraint FK765F0E50A3F58D8D foreign key (modified_by) references person_user;
alter table setting add constraint FK765F0E50E6A2D675 foreign key (person_user) references person_user;
alter table setting add constraint FK765F0E5051A3A90E foreign key (created_by) references person_user;
alter table meeting add constraint FK38264A3B7F1A8A0F foreign key (chair_person) references person;
alter table meeting add constraint FK38264A3B2A9BEA59 foreign key (calendar_event) references calendar_event;
alter table public_holiday add constraint FKEBA2088239175796 foreign key (country) references address_country;
alter table public_holiday add constraint FKEBA208822A9BEA59 foreign key (calendar_event) references calendar_event;
